FROM ubuntu:latest

RUN apt-get update && apt-get install python3 python3-pip iptables python3-dev build-essential python3-venv iw wireless-tools ethtool iproute2 net-tools -y

WORKDIR /app

# สร้าง Virtual Environment
RUN python3 -m venv /env

# ใช้ Virtual Environment
RUN /env/bin/pip install flask

COPY app.py /app
COPY iptables.rules /etc/iptables.rules

EXPOSE 5000

USER root

CMD iptables-restore < /etc/iptables.rules && /env/bin/python /app/app.py && /bin/bash

